### ISSUE TITLE
Needs metadata

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Biomass-Drought#1]
Note: There are two components to this extension.  The drought generator and the drought disturbance.  Both need to be rebuilt and the installer should include both dlls.

**Comment by aruzicka555** [comment]
Pull request submitted - ready for testing.

**Comment by bmarron18** [comment]
First round QAQC has runtime errors,

Internal error occurred within the program: Unable to cast object of type 'System.Int32[]' to type 'System.Double[]'.

Stack trace: at Landis.Library.Metadata.DataTableExtensions.AddDataObject(DataTable tbl, Object dataObject)
at Landis.Library.Metadata.DataTableExtensions.AppendDataObjects(DataTable tbl, IEnumerable dataObjects)
at Landis.Library.Metadata.MetadataTable`1.WriteToFile()
at Landis.Extension.DroughtDisturbance.PlugIn.Run()
at Landis.Model.Run(ExtensionMain extension)
at Landis.Model.Run(String scenarioPath, IUserInterface ui)
at Landis.App.Main(String[] args)

**Comment by rmscheller** [comment]
Bruce and Austen - Is this issue closed?  Thanks!

**Comment by bmarron18** [comment]
QAQC passed; please close issue.
