### ISSUE TITLE
Can or does this extension work with NECN?

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Biomass-Drought#6]
Is it possible for biomass-drought to work with NECN?  Brian Miranda notes that it should NOT be used with PnET because that would duplicate some of the functions within PnET.

**Comment by bmarron18** [comment]
No, Extension-Biomass-Drought does not currently work with NECN succession. The following exceptions were thrown,

Running Drought Disturbance ...
   Processing Drought Disturbance ...
Internal error occurred within the program:
  Object reference not set to an instance of an object.

Stack trace:
   at Landis.Extension.Succession.Biomass.ForestFloor.AddWoody(Double woodyBiomass, ISpecies species, ActiveSite site)
   at Landis.Extension.DroughtDisturbance.PlugIn.Run()
   at Landis.Model.Run(ExtensionMain extension)
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)

**Comment by rmscheller** [comment]
OK, thanks!
